### ISSUE TITLE
50+ characters bug

### ISSUE THREAD

**Issue by nope-dot-jpg** [llakssz/CIAngel#83] opened 2016-05-20 19:14 UTC
There is a bug in the application ; if you type more than 50 characters in any search field, the topscreen will be filled with characters
![top_0000](https://cloud.githubusercontent.com/assets/19495269/15439110/c89c45fc-1ecf-11e6-902e-d0e73d4e673d.png)

**Comment by noirscape** [comment] 2016-05-20 19:28
Are there any games with more than 50 characters? Otherwise this is a wontfix issue as there is little need to fix it.

**Comment by nope-dot-jpg** [comment] 2016-05-20 20:01
No, but it's a bug, so it should be fixed. What kind of dev tolerates bugs in his applications?

**Comment by Masamune3210** [comment] 2016-05-21 03:53
The ones who have other things to do. There is no reason to fix a bug if there is no normal use case to trigger said bug

**Comment by wedr2** [comment] 2016-05-21 04:21
Yes, I can confirm there is a game that uses 60 letters in total:

Game is "Downtown Special: Kunio-kun no Jidaigeki da yo Zen'in Shūgō!", which is on Virtual Console for 3DS.

EDIT: If you want a NA region game, it is "Adventure Time: Hey Ice King! Why'd you steal our garbage?" for Nintendo 3DS.

If you want another one, it is "Puzzle & Dragons Z + Puzzle & Dragons: Super Mario Bros. Edition" for Nintendo 3DS.

EDIT 2: If you want an EU region game, it is "Mario & Sonic at the London 2012 Olympic Games: Virtual Card Album", which is 66 letters long.

**Comment by Masamune3210** [comment] 2016-05-21 06:37
Ok, was unaware that there were so many long winded titles in the 3DS library. Sorry

**Comment by noirscape** [comment] 2016-05-21 10:08
@wedr2 Yeah... then it should be fixed.

**Comment by DrakiaXYZ** [comment] 2016-05-21 19:16
Okay, I plan on fixing this, but have you guys actually USED the search function?

The first two games you mention aren't even in the DB, so using them as examples is pointless. 
Puzzle & Dragons Z + Blah blah can be found by searching "Puzzle Dragon Mario" (Or if you're really lazy, PZDM).
Mario & Sonic blah blah can be found by searching "Mario Sonic". And the name in the DB is "Mario & Sonic - London 2012 Virtual Card Album"

None of the examples given provide a meaningful reason to fix this, since none of them need to be searched for by typing 50+ characters.

**Comment by DrakiaXYZ** [comment] 2016-05-21 20:37
#89

**Comment by nope-dot-jpg** [comment] 2016-05-21 20:42
You should set it to 49 because the bug occurs right at 50

**Comment by DrakiaXYZ** [comment] 2016-05-21 20:43
Had the wrong name on the commit, it only shows 49

**Closed as completed** 2016-05-23 19:03 UTC
